Models/Factura.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System;
using System.Collections.Generic;

namespace Modulo_Facturacion.Models;

public partial class Factura
{
    public int Id { get; set; }

    public int IdVendedor { get; set; }

    public int IdCliente { get; set; }

    public DateTime Fecha { get; set; }

    public string? Comentario { get; set; }

    public int IdArticulo { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    [ValidateNever]
    public virtual Articulo IdArticuloNavigation { get; set; } = null!;

    [ValidateNever]
    public virtual Cliente IdClienteNavigation { get; set; } = null!;

    [ValidateNever]
    public virtual Empleado IdVendedorNavigation { get; set; } = null!;
}

Controllers/FacturasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modulo_Facturacion.Models;

namespace Modulo_Facturacion.Controllers
{
    public class FacturasController : Controller
    {
        private readonly SistemaFacturacionContext _context;

        public FacturasController(SistemaFacturacionContext context)
        {
            _context = context;
        }

        // GET: Facturas
        public async Task<IActionResult> Index()
        {
            var sistemaFacturacionContext = _context.Facturas.Include(f => f.IdArticuloNavigation).Include(f => f.IdClienteNavigation).Include(f => f.IdVendedorNavigation);
            return View(await sistemaFacturacionContext.ToListAsync());
        }

        // GET: Facturas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var factura = await _context.Facturas
                .Include(f => f.IdArticuloNavigation)
                .Include(f => f.IdClienteNavigation)
                .Include(f => f.IdVendedorNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (factura == null)
            {
                return NotFound();
            }

            return View(factura);
        }

        // GET: Facturas/Create
        public IActionResult Create()
        {
            var precioArticulo = _context.Articulos.Select(a => new { a.Id, a.PrecioUnitario }).ToList();

            ViewData["IdArticulo"] = new SelectList(_context.Articulos, "Id", "Descripcion");
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "Id", "Nombre");
            ViewData["IdVendedor"] = new SelectList(_context.Empleados, "Id", "Nombre");
            ViewData["PreciosUnitarios"] = precioArticulo.Select(a => a.PrecioUnitario).ToArray();

            return View();
        }

        // POST: Facturas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdVendedor,IdCliente,Fecha,Comentario,IdArticulo,Cantidad,PrecioUnitario")] Factura factura)
        {
            if (ModelState.IsValid)
            {
                _context.Add(factura);
                await _context.SaveChangesAsync();


                var cliente = await _context.Clientes.FindAsync(factura.IdCliente);

                if (cliente != null)
                {
                    var montoAsiento = factura.Cantidad * factura.PrecioUnitario;
                    var tipoMovimiento = "";

                    if (cliente.CuentaContable == "13")
                    {
                        tipoMovimiento = "DB";
                    }
                    else{
                        tipoMovimiento = "CR";
                    }
                    

                    var asiento = new Asiento
                    {
                        FechaAsiento = DateOnly.FromDateTime(factura.Fecha),
                        IdentificadorCuenta = int.Parse(cliente.CuentaContable),
                        TipoMovimiento = tipoMovimiento,
                        MontoAsiento = montoAsiento
                    };

                    // Agregar el asiento al contexto
                    _context.Asientos.Add(asiento);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            // Registrar los errores de ModelState
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    // Aquí puedes usar una herramienta de logging, como NLog o Serilog
                    Console.WriteLine(error.ErrorMessage); // o registra el error de otra manera
                }
            }

            var precioArticulo = _context.Articulos.Select(a => new { a.Id, a.PrecioUnitario }).ToList();

            ViewData["IdArticulo"] = new SelectList(_context.Articulos, "Id", "Descripcion", factura.IdArticulo);
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "Id", "Nombre", factura.IdCliente);
            ViewData["IdVendedor"] = new SelectList(_context.Empleados, "Id", "Nombre", factura.IdVendedor);
            ViewData["PreciosUnitarios"] = precioArticulo.Select(a => a.PrecioUnitario).ToArray();
            return View(factura);
        }

        // GET: Facturas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var factura = await _context.Facturas.FindAsync(id);
            if (factura == null)
            {
                return NotFound();
            }
            var precioArticulo = _context.Articulos.Select(a => new { a.Id, a.PrecioUnitario }).ToList();

            ViewData["IdArticulo"] = new SelectList(_context.Articulos, "Id", "Descripcion", factura.IdArticulo);
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "Id", "Nombre", factura.IdCliente);
            ViewData["IdVendedor"] = new SelectList(_context.Empleados, "Id", "Nombre", factura.IdVendedor);
            ViewData["PreciosUnitarios"] = precioArticulo.Select(a => a.PrecioUnitario).ToArray();
            return View(factura);
        }

        // POST: Facturas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdVendedor,IdCliente,Fecha,Comentario,IdArticulo,Cantidad,PrecioUnitario")] Factura factura)
        {
            if (id != factura.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(factura);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacturaExists(factura.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var precioArticulo = _context.Articulos.Select(a => new { a.Id, a.PrecioUnitario }).ToList();

            ViewData["IdArticulo"] = new SelectList(_context.Articulos, "Id", "Descripcion", factura.IdArticulo);
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "Id", "Nombre", factura.IdCliente);
            ViewData["IdVendedor"] = new SelectList(_context.Empleados, "Id", "Nombre", factura.IdVendedor);
            ViewData["PreciosUnitarios"] = precioArticulo.Select(a => a.PrecioUnitario).ToArray();
            return View(factura);
        }

        // GET: Facturas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var factura = await _context.Facturas
                .Include(f => f.IdArticuloNavigation)
                .Include(f => f.IdClienteNavigation)
                .Include(f => f.IdVendedorNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (factura == null)
            {
                return NotFound();
            }

            return View(factura);
        }

        // POST: Facturas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var factura = await _context.Facturas.FindAsync(id);
            if (factura != null)
            {
                _context.Facturas.Remove(factura);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FacturaExists(int id)
        {
            return _context.Facturas.Any(e => e.Id == id);
        }
    }
}

Views/Facturas/Create.cshtml
@model Modulo_Facturacion.Models.Factura

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="page-inner">
        <div class="page-header">
            <h3 class="fw-bold mb-3">Facturas</h3>
            <ul class="breadcrumbs mb-3">
                <li class="nav-home">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Facturas" asp-action="Index">
                        Facturas
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Crear Nueva Factura</a>
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Crear Factura:</div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <form asp-action="Create" class="row">
                                <div asp-validation-summary="All" class="text-danger"></div>


                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="IdVendedor">Nombre del Vendedor:</label>
                                        <select class="form-select form-control-lg" asp-for="IdVendedor" asp-items="ViewBag.IdVendedor" required>
                                            <option value="" disabled selected>
                                                -- Selecciona una opción --
                                            </option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="IdCliente">Nombre del Cliente:</label>
                                        <select class="form-select form-control-lg" asp-for="IdCliente" asp-items="ViewBag.IdCliente" required>
                                            <option value="" disabled selected>
                                                -- Selecciona una opción --
                                            </option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="IdArticulo">Articulo:</label>
                                        <select class="form-select form-control-lg" asp-for="IdArticulo" asp-items="ViewBag.IdArticulo" required>
                                            <option value="" disabled selected>
                                                -- Selecciona una opción --
                                            </option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="PrecioUnitario"></label>
                                        <input type="number"
                                               class="form-control form-control-lg"
                                               asp-for="PrecioUnitario"
                                               placeholder="Precio Unitario del Articulo"
                                               required 
                                               readonly/>
                                        <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="Cantidad"></label>
                                        <input type="number"
                                               class="form-control form-control-lg"
                                               asp-for="Cantidad"
                                               placeholder="Ingrese una cantidad"
                                               min="1"
                                               required/>
                                        <span asp-validation-for="Cantidad" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="Fecha"></label>
                                        <input class="form-control form-control-lg"
                                               asp-for="Fecha"
                                               required/>
                                        <span asp-validation-for="Fecha" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="col-md-12 col-lg-12">
                                    <div class="form-group">
                                        <label asp-for="Comentario">Comentarios</label>
                                        <textarea
                                            class="form-control"
                                            asp-for="Comentario"
                                            rows="5"
                                        ></textarea>
                                    </div>
                                </div>

                                <div class="col-md-12 col-lg-12 text-center mt-4">
                                    <input type="submit"
                                           value="Crear Factura"
                                           class="btn btn-primary btn-lg" />
                                    <a asp-action="Index" class="btn btn-warning btn-lg">
                                        Volver Atrás
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await
    Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        // Obtener el array de precios unitarios desde ViewData
        var preciosUnitarios = @Html.Raw(Json.Serialize(ViewData["PreciosUnitarios"]));

        // Manejar el cambio de selección del artículo
        document.querySelector('select[name="IdArticulo"]').addEventListener('change', function(event) {
            var selectedIndex = event.target.selectedIndex;
            var precioUnitario = preciosUnitarios[selectedIndex - 1]; // -1 porque el índice 0 es la opción por defecto en select
            
            // Asignar el precio unitario al input
            document.getElementById('PrecioUnitario').value = precioUnitario ? precioUnitario : '';
        });
    </script>
}

<!--<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Factura</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdVendedor" class="control-label"></label>
                <select asp-for="IdVendedor" class ="form-control" asp-items="ViewBag.IdVendedor"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <select asp-for="IdCliente" class ="form-control" asp-items="ViewBag.IdCliente"></select>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="control-label"></label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdArticulo" class="control-label"></label>
                <select asp-for="IdArticulo" class ="form-control" asp-items="ViewBag.IdArticulo"></select>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioUnitario" class="control-label"></label>
                <input asp-for="PrecioUnitario" class="form-control" />
                <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>-->

Views/Facturas/Delete.cshtml
@model Modulo_Facturacion.Models.Factura

@{
   ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="page-inner">
        <div class="page-header">
            <h3 class="fw-bold mb-3">Facturas</h3>
            <ul class="breadcrumbs mb-3">
                <li class="nav-home">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Facturas" asp-action="Index">
                        Facturas
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Eliminar Factura</a>
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Eliminar Factura: <br /> Si elimina esta factura no podrá recuperarla. </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Vendedor</label>
                                    <input type="text"
                                           class="form-control form-control-lg"
                                           value="@Html.DisplayFor(model => model.IdVendedorNavigation.Nombre)"
                                           disabled />
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Cliente</label>
                                    <input type="text"
                                           class="form-control form-control-lg"
                                           value="@Html.DisplayFor(model => model.IdClienteNavigation.Nombre)"
                                           disabled />
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Articulo</label>
                                    <input type="text"
                                           class="form-control form-control-lg"
                                           value="@Html.DisplayFor(model => model.IdArticuloNavigation.Descripcion)"
                                           disabled />
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Precio Unitario</label>
                                    <div class="input-group mb-3">
                                        <input type="number"
                                               class="form-control form-control-lg"
                                               value="@Html.DisplayFor(model => model.PrecioUnitario)"
                                               aria-describedby="basic-addon2"
                                               disabled />
                                        <span class="input-group-text" id="basic-addon2">.00</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Cantidad</label>
                                    <input type="number"
                                           class="form-control form-control-lg"
                                           value="@Html.DisplayFor(model => model.Cantidad)"
                                           disabled />
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Fecha</label>
                                    <input type="text"
                                           class="form-control form-control-lg"
                                           value="@Html.DisplayFor(model => model.Fecha)"
                                           disabled />
                                </div>
                            </div>

                            <div class="col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label asp-for="Comentario">Comentarios</label>
                                        <textarea
                                            class="form-control"
                                            value="@Html.DisplayFor(model => model.Comentario)"
                                            rows="5"
                                            disabled
                                        ></textarea>
                                </div>
                            </div>


                            <form asp-action="Delete">
                                <input type="hidden" asp-for="Id" />
                                <div class="col-md-12 col-lg-12 text-center mt-4">
                                    <input type="submit"
                                           value="Eliminar Factura"
                                           class="btn btn-danger btn-lg" />
                                    <a asp-action="Index" class="btn btn-warning btn-lg">
                                        Volver Atrás
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Factura</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comentario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdArticuloNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdArticuloNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdClienteNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdClienteNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdVendedorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdVendedorNavigation.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>-->