Models/Empleado.cs
using System;
using System.Collections.Generic;

namespace Modulo_Facturacion.Models;

public partial class Empleado
{
    public int Id { get; set; }

    public string Nombre { get; set; } = null!;

    public int PorcientoComision { get; set; }

    public string Estado { get; set; } = null!;

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}

Models/EmpleadoViewModel.cs
namespace Modulo_Facturacion.Models
{
    public class EmpleadoViewModel
    {
        public int EmpleadoId { get; set; }
        public int Count { get; set; }
        public string Empleado { get; set; }
    }
}

Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modulo_Facturacion.Models;
using Microsoft.AspNetCore.Authorization;

namespace Modulo_Facturacion.Controllers
{
    [Authorize]
    public class EmpleadosController : Controller
    {
        private readonly SistemaFacturacionContext _context;

        public EmpleadosController(SistemaFacturacionContext context)
        {
            _context = context;
        }

        // GET: Empleados
        public async Task<IActionResult> Index()
        {
            return View(await _context.Empleados.ToListAsync());
        }

        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empleados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,PorcientoComision,Estado")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,PorcientoComision,Estado")] Empleado empleado)
        {
            if (id != empleado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado != null)
            {
                _context.Empleados.Remove(empleado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleados.Any(e => e.Id == id);
        }
    }
}

Views/Empleados/Create.cshtml
@model Modulo_Facturacion.Models.Empleado

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="page-inner">
        <div class="page-header">
            <h3 class="fw-bold mb-3">Empleados</h3>
            <ul class="breadcrumbs mb-3">
                <li class="nav-home">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Empleados" asp-action="Index">
                        Empleados
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Crear Nuevo Empleado</a>
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Crear Empleado:</div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <form asp-action="Create">
                                <div asp-validation-summary="ModelOnly"
                                     class="text-danger"></div>
                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="Nombre"></label>
                                        <input type="text"
                                               class="form-control form-control-lg"
                                               asp-for="Nombre"
                                               placeholder="Nombre del Empleado"
                                               required />
                                        <span asp-validation-for="Nombre"
                                              class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="PorcientoComision"></label>
                                        <div class="input-group mb-3">
                                            <input type="number"
                                                   class="form-control form-control-lg"
                                                   asp-for="PorcientoComision"
                                                   placeholder="Por ciento de comision"
                                                   aria-label="Por ciento de comision"
                                                   aria-describedby="basic-addon2"
                                                   min="0"
                                                   required />
                                            <span class="input-group-text" id="basic-addon2">%</span>
                                        </div>
                                        <span asp-validation-for="PorcientoComision"
                                              class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="Estado">Estado</label>
                                        <select class="form-select form-control-lg"
                                                asp-for="Estado"
                                                required>
                                            <option value="" disabled selected>
                                                -- Selecciona una opción --
                                            </option>
                                            <option value="activo  ">Activo</option>
                                            <option value="inactivo">Inactivo</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12 col-lg-12 text-center mt-4">
                                    <input type="submit"
                                           value="Create"
                                           class="btn btn-primary btn-lg" />
                                    <a asp-action="Index" class="btn btn-warning btn-lg">
                                        Volver Atrás
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Empleados/Delete.cshtml
@model Modulo_Facturacion.Models.Empleado

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="page-inner">
        <div class="page-header">
            <h3 class="fw-bold mb-3">Empleados</h3>
            <ul class="breadcrumbs mb-3">
                <li class="nav-home">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Empleados" asp-action="Index">
                        Empleados
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Eliminar Empleado</a>
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Eliminar Empleado: <br /> Si elimina este empleado no podrá recuperarlo. </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Nombre</label>
                                    <input type="text"
                                           class="form-control form-control-lg"
                                           value="@Html.DisplayFor(model => model.Nombre)"
                                           disabled />
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Por Ciento de Comisión</label>
                                    <div class="input-group mb-3">
                                        <input type="number"
                                               class="form-control form-control-lg"
                                               value="@Html.DisplayFor(model => model.PorcientoComision)"
                                               aria-describedby="basic-addon2"
                                               disabled />
                                        <span class="input-group-text" id="basic-addon2">%</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label>Estado</label>
                                    <input type="text"
                                           class="form-control form-control-lg"
                                           value="@Html.DisplayFor(model => model.Estado)"
                                           disabled />
                                </div>
                            </div>

                            <form asp-action="Delete">
                                <input type="hidden" asp-for="Id" />
                                <div class="col-md-12 col-lg-12 text-center mt-4">
                                    <input type="submit"
                                           value="Delete"
                                           class="btn btn-danger btn-lg" />
                                    <a asp-action="Index" class="btn btn-warning btn-lg">
                                        Volver Atrás
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Empleados/Details.cshtml
@model Modulo_Facturacion.Models.Empleado

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PorcientoComision)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PorcientoComision)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Empleados/Edit.cshtml
@model Modulo_Facturacion.Models.Empleado

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="page-inner">
        <div class="page-header">
            <h3 class="fw-bold mb-3">Empleados</h3>
            <ul class="breadcrumbs mb-3">
                <li class="nav-home">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Empleados" asp-action="Index">
                        Empleados
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Editar Empleado</a>
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Editar Empleado:</div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <form asp-action="Edit">
                                <div asp-validation-summary="ModelOnly"
                                     class="text-danger"></div>
                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="Nombre"></label>
                                        <input type="text"
                                               class="form-control form-control-lg"
                                               asp-for="Nombre"
                                               placeholder="Nombre del Empleado"
                                               required />
                                        <span asp-validation-for="Nombre"
                                              class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="PorcientoComision"></label>
                                        <div class="input-group mb-3">
                                            <input type="number"
                                                   class="form-control form-control-lg"
                                                   asp-for="PorcientoComision"
                                                   placeholder="Por ciento de comision"
                                                   aria-label="Por ciento de comision"
                                                   aria-describedby="basic-addon2"
                                                   min="0"
                                                   required />
                                            <span class="input-group-text" id="basic-addon2">%</span>
                                        </div>
                                        <span asp-validation-for="PorcientoComision"
                                              class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label asp-for="Estado">Estado</label>
                                        <select class="form-select form-control-lg"
                                                asp-for="Estado"
                                                required>
                                            <option value="" disabled selected>
                                                -- Selecciona una opción --
                                            </option>
                                            <option value="activo  ">Activo</option>
                                            <option value="inactivo">Inactivo</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12 col-lg-12 text-center mt-4">
                                    <input type="submit"
                                           value="Save"
                                           class="btn btn-primary btn-lg" />
                                    <a asp-action="Index" class="btn btn-warning btn-lg">
                                        Volver Atrás
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Empleados/Index.cshtml
@model IEnumerable<Modulo_Facturacion.Models.Empleado>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="page-inner">
        <div class="page-header">
            <h3 class="fw-bold mb-3">
                Empleados
            </h3>
            <ul class="breadcrumbs mb-3">
                <li class="nav-home">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="fas fa-chevron-right"></i>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Empleados" asp-action="Index">
                        Empleados
                    </a>
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            Añadir un nuevo Empleado
                        </div>
                    </div>
                    <div class="card-body">
                        <a asp-action="Create" class="btn btn-primary btn-lg">
                            Crear Empleado
                        </a>
                    </div>
                </div>

                <div class="col-md-12 text-center">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                Lista de Empleados
                            </div>
                        </div>
                        <div class="card-body">
                            <table class="table table-hover table-head-bg-primary table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">
                                            @Html.DisplayNameFor(model => model.Nombre)
                                        </th>
                                        <th scope="col">
                                            @Html.DisplayNameFor(model => model.PorcientoComision)
                                        </th>
                                        <th scope="col">
                                            @Html.DisplayNameFor(model => model.Estado)
                                        </th>
                                        <th scope="col">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.PorcientoComision)%
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Estado)
                                            </td>
                                            <td>
                                                <a asp-action="Edit"
                                                   asp-route-id="@item.Id"
                                                   class="btn btn-warning">
                                                    <span class="btn-label">
                                                        <i class="fa fa-edit"></i>
                                                    </span>
                                                    Editar
                                                </a>
                                                |
                                                <a asp-action="Delete"
                                                   asp-route-id="@item.Id"
                                                   class="btn btn-danger">
                                                    <span class="btn-label">
                                                        <i class="fa fa-exclamation-circle"></i>
                                                    </span>
                                                    Eliminar
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>